output.elasticsearch:
  hosts: ['${ES_HOSTS}']
setup.kibana:
  enabled: true
  host: '${KIBANA_HOST}'

cloud.auth: '${ES_USER}:${ES_PASS}'
cloud.id: '${CLOUD_AUTH_TOKEN}'

setup.dashboards:
  enabled: true

metricbeat.modules:
   - module: oracle
     metricsets: ["performance", "tablespace"]
     hosts: ["oracle://${DB_USER}:${DB_PASS}@${DB_HOST}"]
     username: '${DB_USER}'
     password: '${DB_PASS}'

  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      - core           # Per CPU core usage
      - diskio         # Disk IO
      - filesystem     # File system usage for each mountpoint
      - fsstat         # File system summary metrics
    enabled: true
    period: 10s
    processes: ['.*']

    cpu.metrics:  [percentages, normalized_percentages, ticks]
    core.metrics: [percentages, ticks]

  - module: system
    metricsets: [socket]
    period: 1s

    socket.reverse_lookup.enabled: false
    socket.reverse_lookup.success_ttl: 60s
    socket.reverse_lookup.failure_ttl: 60s
